export default {
  port: process.env.PORT,
  dbUri: process.env.DB_URL,
  frontendUrl: process.env.FRONTEND_URL,
  logLevel: "info",
  accessTokenTl: "1h",
  refreshTokenTl: "1y",
  forgotPasswordTokenSecret: process.env.FORGOT_PASSWORD_TOKEN_SECRET,
  accessTokenPrivateKey: process.env.ACCESS_TOKEN_PRIVATE_KEY,
  accessTokenPublicKey: process.env.ACCESS_TOKEN_PUBLIC_KEY,
  refreshTokenPrivateKey: process.env.REFRESH_TOKEN_PRIVATE_KEY,
  refreshTokenPublicKey: process.env.REFRESH_TOKEN_PUBLIC_KEY,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleRedirectUri: process.env.CALLBACK_URL,
  mailHost: process.env.MAIL_HOST,
  mailPort: Number(process.env.MAIL_PORT),
  mailUser: process.env.MAIL_USER,
  mailPass: process.env.MAIL_PASS,
  cloudName: process.env.CLOUDINARY_CLOUD_NAME,
  apiKey: process.env.CLOUDINARY_API_KEY,
  apiSecret: process.env.CLOUDINARY_API_SECRET,
};
